# Generated by Django 3.2.19 on 2023-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230607_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
